---
name: Updatecli policies

valuesinline:
  scm:
    enabled: true
    kind: github
    owner: neuvector
    repository: .github
    branch: main
    commitusingapi: true
    user: "updatecli-bot"
    email: "neuvector-bot@users.noreply.github.com"
    commitmessage:
      footers: "Signed-off-by: NeuVector bot <neuvector-bot@users.noreply.github.com>"

include:
  - "updatecli/updatecli-compose.yaml"

policies:
  - name: Local policies
    id: local
    config:
      - "updatecli/updatecli.d"
