---
name: Updatecli policies applied to neuvector/.github

valuesinline:
  scm:
    enabled: true
    kind: githubsearch
    # Right the github runner disk space is too small to clone
    # all GitHub repository in the Neuvector organisation
    # so we restrict the number of repository but at some
    # point, we should be using `org:neuvector` to ensure
    # that any new repositories contains the required gha workflows
    search: |
      repo:neuvector/.github
      repo:neuvector/neuvector
      repo:neuvector/helm
      repo:neuvector/docs
      repo:neuvector/neuvector-runtime-enforcer-policy-converter
      repo:neuvector/neuvector-runtime-enforcer-policy-converter
      archived:false
      fork:false
      is:public
    branch: "^main$|^master$"
    commitusingapi: true
    user: updateclibot
    limit: 0
    email: "neuvector-kubewarden-policy-converter-bot@users.noreply.github.com"
    commitmessage:
      footers: "Signed-off-by: NeuVectorKubewardenPolicyConverter bot <neuvector-kubewarden-policy-converter-bot@users.noreply.github.com>"

policies:
  - name: Handle Updatecli version in GitHub action
    id: updatecli
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.9.1@sha256:49c07d724474ff7976f7ad5ecb0db9aa46448b456d08f82717913b403a0f02d8
    valuesinline:
      pipeline:
        labels:
          ecosystem: updatecli
          monitor: active

  - name: Install Zizmor
    id: zizmor
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.8.1@sha256:f8edda1a6cbf0d7274e2b847ede29fc4dc70dd5302ccb8575ae21b069cc0d8a0
    valuesinline:
      config:
        rules:
          secrets-outside-env:
            disable: true
      autofix:
        enabled: true
        mode: all

  - name: Install Typos
    id: typos
    policy: ghcr.io/updatecli/policies/updatecli/githubaction:0.9.1@sha256:49c07d724474ff7976f7ad5ecb0db9aa46448b456d08f82717913b403a0f02d8
